/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Painels;

import Controllers.OperadoraDAOImpl;
import Controllers.ListaDAOImpl;
import Modelos.Operadora;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matavele's
 */
public class FornecedorR extends javax.swing.JPanel {

    private OperadoraDAOImpl gestor;
    private BufferedImage image;
    private DefaultTableModel modelo;

    /**
     * Creates new form Venda
     */
    public FornecedorR() {
        gestor = new OperadoraDAOImpl();
        initComponents();
        try {
            // Carregue a imagem desejada (substitua o caminho pelo caminho do seu arquivo de imagem)
            image = ImageIO.read(new File("src//Icones//Abstract-Wallpaper-HD-For-Desktop.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        add.putClientProperty("JButton.buttonType", "roundRect");
        edit.putClientProperty("JButton.buttonType", "roundRect");
        rmv.putClientProperty("JButton.buttonType", "roundRect");
        modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Nome");
        modelo.addColumn("Contacto");
        modelo.addColumn("Descrição");
        modelo.addColumn("Entrada");
        tabela();

    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            g.drawImage(image, 0, 0, this);
            
        }else{
           JOptionPane.showInternalMessageDialog(null, "eeee");
        }
    }

    public void tabela() {
        modelo.setRowCount(0);

        List fornecedores = gestor.listarOperadoras();

        Iterator it = fornecedores.iterator();

        while (it.hasNext()) {
            Operadora forn = (Operadora) it.next();

            Object[] fila = new Object[5];

            fila[0] = forn.getId();
            fila[1] = forn.getNome();
            fila[2] = forn.getDescricao();
            fila[3] = forn.getDescricao();
            fila[4] = forn.getEntrada();

            modelo.addRow(fila);
        }
        tabela.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new Views.Painels.PanelBorder();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelBorder3 = new Views.Painels.PanelBorder();
        jLabel2 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        contField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        descField = new javax.swing.JTextField();
        panelBorder4 = new Views.Painels.PanelBorder();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        rmv = new javax.swing.JButton();
        panelBorder2 = new Views.Painels.PanelBorder();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        panelBorder1.setPreferredSize(new java.awt.Dimension(500, 230));
        panelBorder1.setLayout(new java.awt.GridLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        panelBorder1.add(jScrollPane4);

        panelBorder3.setLayout(new java.awt.GridLayout(7, 0));

        jLabel2.setText("Operadora");
        panelBorder3.add(jLabel2);

        nomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldActionPerformed(evt);
            }
        });
        panelBorder3.add(nomeField);

        jLabel1.setText("Contacto");
        panelBorder3.add(jLabel1);

        contField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contFieldActionPerformed(evt);
            }
        });
        panelBorder3.add(contField);

        jLabel9.setText("Descrição");
        panelBorder3.add(jLabel9);
        panelBorder3.add(descField);

        panelBorder4.setLayout(new java.awt.GridLayout());

        add.setText("Registrar");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        panelBorder4.add(add);

        edit.setText("Atualizar");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        panelBorder4.add(edit);

        rmv.setText("Remover");
        panelBorder4.add(rmv);

        panelBorder3.add(panelBorder4);

        panelBorder1.add(panelBorder3);

        add(panelBorder1);

        panelBorder2.setPreferredSize(new java.awt.Dimension(600, 260));
        panelBorder2.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Operadoras Disponiveis");
        panelBorder2.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        panelBorder2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(panelBorder2);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldActionPerformed

    private void contFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contFieldActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       String nome = nomeField.getText();
        String contato = contField.getText();
        String desc = descField.getText();

        Operadora forn = new Operadora(nome, contato, desc);

        try {
            gestor.adicionarOperadora(forn);
            JOptionPane.showMessageDialog(null, "Operadora Registrada!");
            nomeField.setText("");
            contField.setText("");
            descField.setText("");
            tabela();
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        List<Operadora> forns = gestor.listarOperadoras();
        int selected = tabela.getSelectedRow();

        if (selected != -1) {
//
        String nome = nomeField.getText();
        String desc = descField.getText();
        String cont = contField.getText();
//
//            //            String nome = JOptionPane.showInputDialog("Editar nome do cliente:", modelo.getValueAt(selected, 1));
//            //            String email = JOptionPane.showInputDialog("Editar email do cliente:", modelo.getValueAt(selected, 1));
            if (nome != null && !nome.isEmpty()) {
                int id = (int) modelo.getValueAt(selected, 0);
                for (Operadora forn : forns) {
                    if (forn.getId() == id) {
                        forn.setNome(nome);
                        forn.setContacto(cont);    
                        gestor.atualizarOperadora(forn);
                    }
                }
                tabela();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma Operadora para editar.");
        }
    }//GEN-LAST:event_editActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField contField;
    private javax.swing.JTextField descField;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nomeField;
    private Views.Painels.PanelBorder panelBorder1;
    private Views.Painels.PanelBorder panelBorder2;
    private Views.Painels.PanelBorder panelBorder3;
    private Views.Painels.PanelBorder panelBorder4;
    private javax.swing.JButton rmv;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
