/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Painels;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author Matavele's
 */
public class Funcionario extends javax.swing.JPanel {
    private BufferedImage image;
    /**
     * Creates new form Funcionario
     */
    public Funcionario() {
        initComponents();
        try {
            // Carregue a imagem desejada (substitua o caminho pelo caminho do seu arquivo de imagem)
            image = ImageIO.read(new File("src//Icones//Abstract-Wallpaper-HD-For-Desktop.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            g.drawImage(image, 0, 0, this);
            
          
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new Views.Painels.PanelBorder();
        imageAvatar1 = new Views.Painels.ImageAvatar();
        panelBorder4 = new Views.Painels.PanelBorder();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelBorder3 = new Views.Painels.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelBorder5 = new Views.Painels.PanelBorder();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        panelBorder2 = new Views.Painels.PanelBorder();
        jLabel4 = new javax.swing.JLabel();
        panelBorder6 = new Views.Painels.PanelBorder();
        panelBorder8 = new Views.Painels.PanelBorder();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        panelBorder1.setPreferredSize(new java.awt.Dimension(500, 200));
        panelBorder1.setLayout(new java.awt.GridLayout());

        imageAvatar1.setLayout(new java.awt.FlowLayout());

        panelBorder4.setLayout(new java.awt.GridLayout(1, 3));

        jButton1.setText("jButton1");
        panelBorder4.add(jButton1);

        jButton2.setText("jButton2");
        panelBorder4.add(jButton2);

        jButton3.setText("jButton3");
        panelBorder4.add(jButton3);

        imageAvatar1.add(panelBorder4);

        panelBorder1.add(imageAvatar1);

        panelBorder3.setLayout(new java.awt.GridLayout(7, 0));

        jLabel1.setText("jLabel1");
        panelBorder3.add(jLabel1);
        panelBorder3.add(jTextField1);

        jLabel2.setText("jLabel2");
        panelBorder3.add(jLabel2);
        panelBorder3.add(jTextField2);

        jLabel3.setText("jLabel3");
        panelBorder3.add(jLabel3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelBorder3.add(jComboBox1);

        panelBorder5.setLayout(new java.awt.GridLayout(1, 3));
        panelBorder5.add(jButton4);

        jButton5.setText("jButton5");
        panelBorder5.add(jButton5);

        jButton6.setText("jButton6");
        panelBorder5.add(jButton6);

        panelBorder3.add(panelBorder5);

        panelBorder1.add(panelBorder3);

        add(panelBorder1);

        panelBorder2.setPreferredSize(new java.awt.Dimension(500, 200));
        panelBorder2.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Informação");
        panelBorder2.add(jLabel4, java.awt.BorderLayout.NORTH);

        panelBorder6.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        panelBorder8.setLayout(new java.awt.GridLayout(7, 0, 10, 5));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("jLabel5:");
        panelBorder8.add(jLabel5);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setEnabled(false);
        panelBorder8.add(jTextField3);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("jLabel6:");
        panelBorder8.add(jLabel6);

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        panelBorder8.add(jTextField4);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("jLabel7:");
        panelBorder8.add(jLabel7);

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        panelBorder8.add(jTextField5);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("jLabel8:");
        panelBorder8.add(jLabel8);

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setEnabled(false);
        panelBorder8.add(jTextField6);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("jLabel9:");
        panelBorder8.add(jLabel9);

        jButton7.setText("Email@example.com");
        jButton7.setContentAreaFilled(false);
        panelBorder8.add(jButton7);

        panelBorder6.add(panelBorder8);

        panelBorder2.add(panelBorder6, java.awt.BorderLayout.CENTER);

        add(panelBorder2);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Views.Painels.ImageAvatar imageAvatar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private Views.Painels.PanelBorder panelBorder1;
    private Views.Painels.PanelBorder panelBorder2;
    private Views.Painels.PanelBorder panelBorder3;
    private Views.Painels.PanelBorder panelBorder4;
    private Views.Painels.PanelBorder panelBorder5;
    private Views.Painels.PanelBorder panelBorder6;
    private Views.Painels.PanelBorder panelBorder8;
    // End of variables declaration//GEN-END:variables
}
