/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Painels;

import Controllers.ClienteDAOImpl;
import Controllers.ListaDAOImpl;
import Controllers.ProdutosDAOImpl;
import Modelos.Categoria;
import Modelos.Cliente;
import Modelos.Lista;
import Modelos.Produto;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matavele's
 */
public class ListaC extends javax.swing.JPanel {

    private ListaDAOImpl gestor;
    private ProdutosDAOImpl gestor1;
    private ClienteDAOImpl gestor2;

    private DefaultTableModel modelo;
    private DefaultComboBoxModel model;
    private DefaultComboBoxModel model2;
    
    private BufferedImage image;

    /**
     * Creates new form Venda
     */
    public ListaC() {

        gestor = new ListaDAOImpl();
        gestor1 = new ProdutosDAOImpl();
        gestor2 = new ClienteDAOImpl();
        initComponents();
        try {
            // Carregue a imagem desejada (substitua o caminho pelo caminho do seu arquivo de imagem)
            image = ImageIO.read(new File("src//Icones//Abstract-Wallpaper-HD-For-Desktop.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        add.putClientProperty("JButton.buttonType", "roundRect");
        edit.putClientProperty("JButton.buttonType", "roundRect");
        Remover.putClientProperty("JButton.buttonType", "roundRect");
        model = new DefaultComboBoxModel();
        model2 = new DefaultComboBoxModel();
        modelo = new DefaultTableModel();
        modelo.addColumn("Cliente");
        modelo.addColumn("Produto");
        modelo.addColumn("Quantidade");
        modelo.addColumn("total");

        combo1();
        combo2();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            g.drawImage(image, 0, 0, this);
            System.out.println("debugging");
        }else{
           JOptionPane.showInternalMessageDialog(null, "eeee");
        }
    }

    public void tabela(Cliente cliente) {
        modelo.setRowCount(0);

        List<Lista> ls = gestor.buscarListaCliente(cliente);

        Iterator it = ls.iterator();

        while (it.hasNext()) {
            
            Lista lista = (Lista) it.next();
            if(lista.isStatus()==true){
            Object[] fila = new Object[4];

            fila[0] = lista.getCliente().getId();
            fila[1] = lista.getProduto().getId();
            fila[2] = lista.getQuantidade();
            fila[3] = lista.getTotal();

            modelo.addRow(fila);
            }

        }

        tabela.setModel(modelo);

    }

    public void combo1() {
        List cat = gestor1.listarProdutos();

        Iterator it = cat.iterator();

        while (it.hasNext()) {

            Produto produto = (Produto) it.next();
            String nome = produto.getNomeProduto();

            model2.addElement(nome);
        }

        combox2.setModel(model2);
    }

    public void combo2() {
        List cat = gestor2.listarCliente();

        Iterator it = cat.iterator();

        while (it.hasNext()) {

            Cliente produto = (Cliente) it.next();
            String nome = produto.getNome();

            model.addElement(nome);
        }

        combox.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        combox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        combox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        qtdField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        Remover = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 500));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel4.setPreferredSize(new java.awt.Dimension(450, 450));
        jPanel4.setLayout(new java.awt.GridLayout(2, 1));

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane4);

        jPanel2.setLayout(new java.awt.GridLayout(7, 0));

        jLabel2.setText("Cliente");
        jPanel2.add(jLabel2);

        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxActionPerformed(evt);
            }
        });
        jPanel2.add(combox);

        jLabel1.setText("Recarga");
        jPanel2.add(jLabel1);

        combox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(combox2);

        jLabel9.setText("Quantidade");
        jPanel2.add(jLabel9);
        jPanel2.add(qtdField);

        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 1, 0));

        add.setText("Adicionar");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel3.add(add);

        edit.setText("Alterar");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel3.add(edit);

        Remover.setText("Remover");
        Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverActionPerformed(evt);
            }
        });
        jPanel3.add(Remover);

        jPanel2.add(jPanel3);

        jPanel5.add(jPanel2);

        jPanel4.add(jPanel5);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Recargas a Comprar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 86, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel4.add(jPanel1);

        jScrollPane2.setViewportView(jPanel4);

        add(jScrollPane2);
    }// </editor-fold>//GEN-END:initComponents

    private void comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxActionPerformed
        int index = combox.getSelectedIndex();
        List<Cliente> clientes = gestor2.listarCliente();
        Cliente cliente = clientes.get(index);
        tabela(cliente);
    }//GEN-LAST:event_comboxActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        int quantidade = Integer.parseInt(qtdField.getText());

        int selectedIndex = combox.getSelectedIndex();
        int selectedIndex1 = combox2.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um Cliente.");
            return;
        }

        if (selectedIndex1 == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma Recarga.");
            return;
        }

        List cat = gestor1.listarProdutos();
        List cat2 = gestor2.listarCliente();

        if ((cat != null && selectedIndex >= 0 && selectedIndex < cat.size())) {
            Produto prod = (Produto) cat.get(selectedIndex1);

            Cliente cliente = (Cliente) cat2.get(selectedIndex);

            List<Lista> lc = gestor.buscarListaCliente(cliente);


                    try {
                        Lista list = new Lista(cliente, prod, quantidade);
                        prod.setQuantidadeProduto(list.getRemanescente());
                        gestor1.atualizarProdutos(prod);
                        try {
                            gestor.adicionarLista(list);
                            JOptionPane.showMessageDialog(null, "Recarga adicionada a lista de compras!");
                            qtdField.setText("");
                            tabela(cliente);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    } catch (NullPointerException e) {
                        JOptionPane.showMessageDialog(null, "excedeu o limite" + e.getMessage());
                    }


        } else {
            JOptionPane.showMessageDialog(null, "Recarga/Cliente selecionado inválido.");
        }
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        List<Cliente> cs = gestor2.listarCliente();
        List<Produto> ps = gestor1.listarProdutos();
        int com = combox.getSelectedIndex();
        int com1 = combox2.getSelectedIndex();

        int selected = tabela.getSelectedRow();

        if (selected != -1) {
            Produto cat1 = ps.get(com1);
            Cliente cat = cs.get(com);
            int quantidade = Integer.parseInt(qtdField.getText());

            //            String nome = JOptionPane.showInputDialog("Editar nome do cliente:", modelo.getValueAt(selected, 1));
            //            String email = JOptionPane.showInputDialog("Editar email do cliente:", modelo.getValueAt(selected, 1));
            if (quantidade != 0) {
                int id = (int) modelo.getValueAt(selected, 0);
                int id1 = (int) modelo.getValueAt(selected, 1);

                Cliente cliente = gestor2.buscarCliente(id);
                Produto produto = gestor1.buscarProduto(id1);

                List<Lista> listas = gestor.buscarListaCliente(cliente);
                for (Lista lista : listas) {
                    if (lista.getProduto().getId() == id1) {
                        lista.setQuantidade(quantidade);
                        produto.setQuantidadeProduto(lista.getRemanescente());

                        gestor.atualizarLista(lista);
                        gestor1.atualizarProdutos(produto);
                    }

                }
                tabela(cliente);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma Recarga para atualizar.");
        }
    }//GEN-LAST:event_editActionPerformed

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
        List<Cliente> cs = gestor2.listarCliente();
        List<Produto> ps = gestor1.listarProdutos();
        int com = combox.getSelectedIndex();
        int com1 = combox2.getSelectedIndex();

        int selected = tabela.getSelectedRow();

        if (selected != -1) {
            Produto cat1 = ps.get(com1);
            Cliente cat = cs.get(com);
            int quantidade = Integer.parseInt(qtdField.getText());

            //            String nome = JOptionPane.showInputDialog("Editar nome do cliente:", modelo.getValueAt(selected, 1));
            //            String email = JOptionPane.showInputDialog("Editar email do cliente:", modelo.getValueAt(selected, 1));
            if (quantidade != 0) {
                int id = (int) modelo.getValueAt(selected, 0);
                int id1 = (int) modelo.getValueAt(selected, 1);

                Cliente cliente = gestor2.buscarCliente(id);
                Produto produto = gestor1.buscarProduto(id1);

                List<Lista> listas = gestor.buscarListaCliente(cliente);
                for (Lista lista : listas) {
                    if (lista.getProduto().getId() == id1) {
                        gestor.removerLista(lista);
                        
                    }

                }
                tabela(cliente);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma Recarga para Eliminar.");
        }
    }//GEN-LAST:event_RemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Remover;
    private javax.swing.JButton add;
    private javax.swing.JComboBox<String> combox;
    private javax.swing.JComboBox<String> combox2;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField qtdField;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
