/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Painels;

import Controllers.ClienteDAOImpl;
import Controllers.ListaDAOImpl;
import Controllers.ProdutosDAOImpl;
import Modelos.Categoria;
import Modelos.Cliente;
import Modelos.Lista;
import Modelos.Produto;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matavele's
 */
public class ListaC extends javax.swing.JPanel {

    private ListaDAOImpl gestor;
    private ProdutosDAOImpl gestor1;
    private ClienteDAOImpl gestor2;

    private DefaultTableModel modelo;
    private DefaultComboBoxModel model;
    private DefaultComboBoxModel model2;

    /**
     * Creates new form Venda
     */
    public ListaC() {

        gestor = new ListaDAOImpl();
        gestor1 = new ProdutosDAOImpl();
        gestor2 = new ClienteDAOImpl();
        initComponents();
        model = new DefaultComboBoxModel();
        model2 = new DefaultComboBoxModel();
        modelo = new DefaultTableModel();
        modelo.addColumn("Cliente");
        modelo.addColumn("Produto");
        modelo.addColumn("Quantidade");
        modelo.addColumn("total");

        combo1();
        combo2();
    }

    public void tabela(Cliente cliente) {
        modelo.setRowCount(0);

        List<Lista> ls = gestor.buscarListaCliente(cliente);

        Iterator it = ls.iterator();

        while (it.hasNext()) {
            
            Lista lista = (Lista) it.next();
            if(lista.isStatus()==true){
            Object[] fila = new Object[4];

            fila[0] = lista.getCliente().getId();
            fila[1] = lista.getProduto().getId();
            fila[2] = lista.getQuantidade();
            fila[3] = lista.getTotal();

            modelo.addRow(fila);
            }

        }

        tabela.setModel(modelo);

    }

    public void combo1() {
        List cat = gestor1.listarProdutos();

        Iterator it = cat.iterator();

        while (it.hasNext()) {

            Produto produto = (Produto) it.next();
            String nome = produto.getNomeProduto();

            model2.addElement(nome);
        }

        combox2.setModel(model2);
    }

    public void combo2() {
        List cat = gestor2.listarCliente();

        Iterator it = cat.iterator();

        while (it.hasNext()) {

            Cliente produto = (Cliente) it.next();
            String nome = produto.getNome();

            model.addElement(nome);
        }

        combox.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        combox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        combox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        qtdField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(2, 2));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(7, 0));

        jLabel2.setText("Cliente");
        jPanel2.add(jLabel2);

        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxActionPerformed(evt);
            }
        });
        jPanel2.add(combox);

        jLabel1.setText("Produto");
        jPanel2.add(jLabel1);

        combox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(combox2);

        jLabel9.setText("Quantidade");
        jPanel2.add(jLabel9);
        jPanel2.add(qtdField);

        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 1, 0));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Adicionar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Editar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Eliminar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4);

        jPanel2.add(jPanel3);

        add(jPanel2);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        add(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        add(jPanel1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        add(jScrollPane4);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked

        int quantidade = Integer.parseInt(qtdField.getText());

        int selectedIndex = combox.getSelectedIndex();
        int selectedIndex1 = combox2.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um Cliente.");
            return;
        }

        if (selectedIndex1 == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um Produto.");
            return;
        }

        List cat = gestor1.listarProdutos();
        List cat2 = gestor2.listarCliente();

        if ((cat != null && selectedIndex >= 0 && selectedIndex < cat.size())) {
            Produto prod = (Produto) cat.get(selectedIndex1);

            Cliente cliente = (Cliente) cat2.get(selectedIndex);

            List<Lista> lc = gestor.buscarListaCliente(cliente);


                    try {
                        Lista list = new Lista(cliente, prod, quantidade);
                        prod.setQuantidadeProduto(list.getRemanescente());
                        gestor1.atualizarProdutos(prod);
                        try {
                            gestor.adicionarLista(list);
                            JOptionPane.showMessageDialog(null, "Produto adicionado a lista de compras!");
                            qtdField.setText("");
                            tabela(cliente);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    } catch (NullPointerException e) {
                        JOptionPane.showMessageDialog(null, "excedeu o limite" + e.getMessage());
                    }


        } else {
            JOptionPane.showMessageDialog(null, "Produto/Cliente selecionado inválido.");
        }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        List<Cliente> cs = gestor2.listarCliente();
        List<Produto> ps = gestor1.listarProdutos();
        int com = combox.getSelectedIndex();
        int com1 = combox2.getSelectedIndex();

        int selected = tabela.getSelectedRow();

        if (selected != -1) {
            Produto cat1 = ps.get(com1);
            Cliente cat = cs.get(com);
            int quantidade = Integer.parseInt(qtdField.getText());

            //            String nome = JOptionPane.showInputDialog("Editar nome do cliente:", modelo.getValueAt(selected, 1));
            //            String email = JOptionPane.showInputDialog("Editar email do cliente:", modelo.getValueAt(selected, 1));
            if (quantidade != 0) {
                int id = (int) modelo.getValueAt(selected, 0);
                int id1 = (int) modelo.getValueAt(selected, 1);

                Cliente cliente = gestor2.buscarCliente(id);
                Produto produto = gestor1.buscarProduto(id1);

                List<Lista> listas = gestor.buscarListaCliente(cliente);
                for (Lista lista : listas) {
                    if (lista.getProduto().getId() == id1) {
                        lista.setQuantidade(quantidade);
                        produto.setQuantidadeProduto(lista.getRemanescente());

                        gestor.atualizarLista(lista);
                        gestor1.atualizarProdutos(produto);
                    }

                }
                tabela(cliente);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Produto para atualizar.");
        }
    }//GEN-LAST:event_jPanel5MouseClicked

    private void comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxActionPerformed
        int index = combox.getSelectedIndex();
        List<Cliente> clientes = gestor2.listarCliente();
        Cliente cliente = clientes.get(index);
        tabela(cliente);
    }//GEN-LAST:event_comboxActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
       List<Cliente> cs = gestor2.listarCliente();
        List<Produto> ps = gestor1.listarProdutos();
        int com = combox.getSelectedIndex();
        int com1 = combox2.getSelectedIndex();

        int selected = tabela.getSelectedRow();

        if (selected != -1) {
            Produto cat1 = ps.get(com1);
            Cliente cat = cs.get(com);
            int quantidade = Integer.parseInt(qtdField.getText());

            //            String nome = JOptionPane.showInputDialog("Editar nome do cliente:", modelo.getValueAt(selected, 1));
            //            String email = JOptionPane.showInputDialog("Editar email do cliente:", modelo.getValueAt(selected, 1));
            if (quantidade != 0) {
                int id = (int) modelo.getValueAt(selected, 0);
                int id1 = (int) modelo.getValueAt(selected, 1);

                Cliente cliente = gestor2.buscarCliente(id);
                Produto produto = gestor1.buscarProduto(id1);

                List<Lista> listas = gestor.buscarListaCliente(cliente);
                for (Lista lista : listas) {
                    if (lista.getProduto().getId() == id1) {
                        gestor.removerLista(lista);
                        
                    }

                }
                tabela(cliente);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Produto para Eliminar.");
        }
    }//GEN-LAST:event_jPanel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combox;
    private javax.swing.JComboBox<String> combox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField qtdField;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
