/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Painels;

import Modelos.Funcionario;
import Views.FreshUi;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.raven.form.Form_Home;
import java.awt.Component;
import java.awt.EventQueue;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javaswingdev.drawer.Drawer;
import javaswingdev.drawer.DrawerController;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import net.miginfocom.layout.ComponentWrapper;
import net.miginfocom.layout.LayoutCallback;
import raven.glasspanepopup.DefaultLayoutCallBack;
import raven.glasspanepopup.DefaultOption;
import raven.glasspanepopup.GlassPanePopup;
import sample.notification.Notifications;

/**
 *
 * @author Matavele's
 */
public class Log extends javax.swing.JPanel {

    private VendaR painelVenda;
    private FornecedorR painelForn;
    private ProdutoR painelProd;
    private ListaC painelLista;
    private CategoriaR painelCateg;
    private ClienteR painelCliente;
    private FuncionarioR painelFunc;
    private Funcionario funcionario;
    private Funcionarios painelfuncionario;
    private DrawerController dr;
    private JFrame frame;
    private BufferedImage image;

    private boolean a = false;

    /**
     * Creates new form Log
     *
     * @param frame
     */
    public Log(JFrame frame, Funcionario func) {
        funcionario = (Funcionario) func;
        painelVenda = new VendaR(funcionario);
        painelForn = new FornecedorR();
        painelProd = new ProdutoR();
        painelLista = new ListaC();
        painelCateg = new CategoriaR();
        painelCliente = new ClienteR();
        painelFunc = new FuncionarioR();
        painelfuncionario = new Funcionarios();
        this.frame = frame;
//        UIManager.put("Button.arc", 999);
        initComponents();

        jPanel9.add(new Form_Home(), java.awt.BorderLayout.CENTER);

        try {
            // Carregue a imagem desejada (substitua o caminho pelo caminho do seu arquivo de imagem)
            image = ImageIO.read(new File("src//Icones//Abstract-Wallpaper-HD-For-Desktop.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }

        jButton1.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton11.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton10.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton12.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton13.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton7.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton20.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton20.putClientProperty("JComponent.minimumHeight", 60);
        jButton21.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton22.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton23.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton24.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton25.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton14.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton2.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton3.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton4.putClientProperty("JButton.buttonType", "toolBarButton");
        jTextField1.putClientProperty("JTextField.leadingComponent", jButton5);
        jTextField1.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Procurar...");
        jTextField1.putClientProperty(FlatClientProperties.STYLE, ""
                + "showClearButton:true");

        

        jPopupMenu1.add(jPanel10);

    }

    public DrawerController getDr() {
        return dr;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            g.drawImage(image, 0, 0, jPanel9);

        } else {
            JOptionPane.showInternalMessageDialog(null, "eeee");
        }

    }

    public JButton getjButton8() {
        return jButton8;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel10 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();

        jPanel10.setLayout(new java.awt.GridLayout(3, 0));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-logout-25.png"))); // NOI18N
        jButton2.setText("Sair");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-male-user-25.png"))); // NOI18N
        jButton3.setText("Perfil");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel10.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Matavele's\\Downloads\\icons8-config-25.png")); // NOI18N
        jButton4.setText("Configurações");
        jButton4.setToolTipText("");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton4);

        jLabel1.setText("jLabel1");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/search_25px.png"))); // NOI18N

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(638, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel12.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });
        jPanel12.setLayout(new java.awt.GridLayout(1, 2));

        jPanel17.setLayout(new java.awt.GridLayout(1, 3));

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/menu_rounded_25px.png"))); // NOI18N
        jButton10.setFocusable(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/eye_25px.png"))); // NOI18N
        jButton12.setFocusable(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton12);

        jButton6.setContentAreaFilled(false);
        jButton6.setFocusable(false);
        jPanel7.add(jButton6);

        jPanel17.add(jPanel7);

        jButton13.setContentAreaFilled(false);
        jButton13.setFocusable(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton13);

        jPanel12.add(jPanel17);

        jPanel1.add(jPanel12, java.awt.BorderLayout.LINE_START);

        jPanel13.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel13.setLayout(new java.awt.GridLayout(1, 3));
        jPanel13.add(jTextField1);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/notification_25px.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);

        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/settings_25px.png"))); // NOI18N
        jButton7.setOpaque(true);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/info_25px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jPanel13.add(jPanel3);

        jPanel1.add(jPanel13, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setToolTipText("");

        jPanel14.setPreferredSize(new java.awt.Dimension(0, 291));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(101, 50));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("GWEVISSA");
        jPanel5.add(jLabel9, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel8.setLayout(new java.awt.GridLayout(10, 0));

        jLabel19.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Principal");
        jPanel8.add(jLabel19);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/customer_40px.png"))); // NOI18N
        jButton20.setText("Clientes");
        jButton20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton20);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/category_40px.png"))); // NOI18N
        jButton21.setText("Categoria");
        jButton21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton21);

        jLabel20.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("Admin");
        jPanel8.add(jLabel20);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/sell_40px.png"))); // NOI18N
        jButton22.setText("Venda");
        jButton22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton22);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/qr_code_40px.png"))); // NOI18N
        jButton23.setText("Recargas");
        jButton23.setHideActionText(true);
        jButton23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton23);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/supplier_40px.png"))); // NOI18N
        jButton24.setText("Operadoras");
        jButton24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton24);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/shopping_40px.png"))); // NOI18N
        jButton25.setText("Lista");
        jButton25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton25);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/conference_foreground_selected_40px.png"))); // NOI18N
        jButton14.setText("Colaboradores");
        jButton14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton14);

        jPanel4.add(jPanel8);

        jPanel14.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.GridLayout(1, 3));

        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("def");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8);

        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("night");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);

        jPanel14.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setViewportView(jPanel14);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.WEST);

        jPanel9.setLayout(new java.awt.BorderLayout());
        jPanel9.add(jPanel11, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel9, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        //create void for methode hide and show panel menu
        //        if (a == true) {
            //            hideshow(jPanel14, a);
            //            SwingUtilities.updateComponentTreeUI(this);
            //            //create methode change image
            //
            //            a = false;
            //        } else {
            //            hideshow(jPanel14, a);
            //            SwingUtilities.updateComponentTreeUI(this);
            //            a = true;
            //        }
        dr = Drawer.newDrawer(frame).header(jPanel5)
                .drawerBackground(UIManager.getColor(ui))
                .enableScroll(true)
                .space(5)
                //                .addChild(new DrawerItem("Clientes").icon(new ImageIcon(getClass().getResource("raven/icon/png/logo.png"))).build())
                .addChild(jButton20)
                .addChild(jButton21)
                .addChild(jButton22)
                .addChild(jButton23)
                .addChild(jButton24)
                .addChild(jButton25)
                .addChild(jButton14)
                .addFooter(jPanel6)
                .build();
            
        if (dr.isShow()) {
            dr.hide();
        } else {
            dr.show();
        }


    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jPanel9.removeAll();

        jPanel9.add(new Form_Home(), java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked

    }//GEN-LAST:event_jPanel12MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        jPopupMenu1.show(jButton7, WIDTH, 50);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        painelCliente = new ClienteR();
        jPanel9.removeAll();
        jPanel9.add(painelCliente, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed

        painelCateg = new CategoriaR();
        jPanel9.removeAll();
        jPanel9.add(painelCateg, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        painelVenda = new VendaR(funcionario);
        jPanel9.removeAll();
        jPanel9.add(painelVenda, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        painelProd = new ProdutoR();
        jPanel9.removeAll();
        jPanel9.add(painelProd, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        painelForn = new FornecedorR();
        jPanel9.removeAll();
        jPanel9.add(painelForn, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        painelLista = new ListaC();
        jPanel9.removeAll();
        jPanel9.add(painelLista, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        FreshUi fresh = (FreshUi) frame;
        fresh.setPanel(fresh.getLogin());
        fresh.setVisible(true);
        revalidate();
        repaint();

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        EventQueue.invokeLater(() -> {
            FlatAnimatedLafChange.showSnapshot();
            FlatMacLightLaf.setup();
            FlatLaf.updateUI();
            FlatAnimatedLafChange.hideSnapshotWithAnimation();

        });
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        EventQueue.invokeLater(() -> {
            FlatAnimatedLafChange.showSnapshot();
            FlatMacDarkLaf.setup();
            FlatLaf.updateUI();
            FlatAnimatedLafChange.hideSnapshotWithAnimation();

        });
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        GlassPanePopup.install(frame);
        GlassPanePopup.showPopup(new Notifications(), new DefaultOption() {
            @Override
            public float opacity() {
                return (float) 0.3;
            }

            @Override
            public LayoutCallback getLayoutCallBack(Component parent) {
                return new DefaultLayoutCallBack(parent) {
                    @Override
                    public void correctBounds(ComponentWrapper cw) {
                        if (parent.isVisible()) {
                            Point pl = parent.getLocationOnScreen();
                            Point bl = jButton11.getLocationOnScreen();
                            int x = bl.x - pl.x;
                            int y = bl.y - pl.y;
                            y += (1f - getAnimate()) * 10f;
                            cw.setBounds(x - cw.getWidth() + jButton11.getWidth(), y + jButton11.getHeight(), cw.getWidth(), cw.getHeight());
                        } else {
                            super.correctBounds(cw);
                        }
                    }
                };
            }

            @Override
            public String getLayout(Component parent, float animate) {
                return null;
            }
        });
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        painelFunc = new FuncionarioR();
        jPanel9.removeAll();
        jPanel9.add(painelFunc, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        painelfuncionario = new Funcionarios();
        jPanel9.removeAll();
        jPanel9.add(painelfuncionario, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
