/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Painels;

import Views.FreshUi;
import java.awt.Color;
import java.awt.Dimension;
import javaswingdev.drawer.Drawer;
import javaswingdev.drawer.DrawerController;
import javax.swing.JFrame;
import raven.toast.Notifications;

/**
 *
 * @author Matavele's
 */
public class Log extends javax.swing.JPanel {
    
    private Venda painelVenda;
    private FornecedorR painelForn;
    private ProdutoR painelProd;
    private ListaC painelLista;
    private CategoriaR painelCateg;
    private ClienteR painelCliente;
    private DrawerController dr;
    private JFrame frame;
    private Notifications note;

    private boolean a = false;
    /**
     * Creates new form Log
     */
    public Log(JFrame frame) {
        painelVenda = new Venda();
        painelForn = new FornecedorR();
        painelProd = new ProdutoR();
        painelLista = new ListaC();
        painelCateg = new CategoriaR();
        painelCliente = new ClienteR();
        this.frame = frame;
//        UIManager.put("Button.arc", 999);
        initComponents();
        
        
        jButton1.putClientProperty("JButton.buttonType", "help");
        jButton11.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton10.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton12.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton13.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton7.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton20.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton20.putClientProperty("JComponent.minimumHeight", 60);
        jButton21.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton22.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton23.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton24.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton25.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton2.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton3.putClientProperty("JButton.buttonType", "toolBarButton");
        jButton4.putClientProperty("JButton.buttonType", "toolBarButton");

        dr = Drawer.newDrawer(frame).header(jPanel5)
                .drawerBackground(new Color(40, 44, 52))
                .enableScroll(true)
                .space(5)
//                .addChild(new DrawerItem("Clientes").icon(new ImageIcon(getClass().getResource("raven/icon/png/logo.png"))).build())
                .addChild(jButton20)
                .addChild(jButton21)
                .addChild(jButton22)
                .addChild(jButton23)
                .addChild(jButton24)
                .addChild(jButton25)
                .addFooter(jPanel6)
                .build();

        jPopupMenu1.add(jPanel10);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel10 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel10.setLayout(new java.awt.GridLayout(3, 0));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-logout-25.png"))); // NOI18N
        jButton2.setText("Sair");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel10.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-male-user-25.png"))); // NOI18N
        jButton3.setText("Perfil");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel10.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Matavele's\\Downloads\\icons8-config-25.png")); // NOI18N
        jButton4.setText("Configurações");
        jButton4.setToolTipText("");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel10.add(jButton4);

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(638, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel12.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });
        jPanel12.setLayout(new java.awt.GridLayout(2, 2));
        jPanel12.add(jLabel2);
        jPanel12.add(jLabel3);

        jPanel17.setLayout(new java.awt.GridLayout(1, 3));

        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-menu-24.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton10);

        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton12);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-notification-25.png"))); // NOI18N
        jPanel17.add(jButton11);

        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton13);

        jPanel12.add(jPanel17);

        jPanel7.setLayout(new java.awt.GridLayout(1, 3));
        jPanel12.add(jPanel7);

        jPanel1.add(jPanel12, java.awt.BorderLayout.LINE_START);

        jPanel13.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel13.setLayout(new java.awt.GridLayout(2, 3));
        jPanel13.add(jLabel15);
        jPanel13.add(jLabel10);
        jPanel13.add(jLabel16);
        jPanel13.add(jLabel12);
        jPanel13.add(jLabel13);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Matavele's\\Downloads\\icons8-tools-25.png")); // NOI18N
        jButton7.setOpaque(true);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jPanel3.add(jButton1);

        jPanel13.add(jPanel3);

        jPanel1.add(jPanel13, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setToolTipText("");

        jPanel14.setPreferredSize(new java.awt.Dimension(0, 291));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(101, 50));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("GWEVISSA.proj");
        jPanel5.add(jLabel9, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel8.setLayout(new java.awt.GridLayout(10, 0));

        jLabel19.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Principal");
        jPanel8.add(jLabel19);

        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-customer-40.png"))); // NOI18N
        jButton20.setText("Clientes");
        jButton20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton20);

        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-product-40.png"))); // NOI18N
        jButton21.setText("Categoria");
        jButton21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton21);

        jLabel20.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("Admin");
        jPanel8.add(jLabel20);

        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-sell-40.png"))); // NOI18N
        jButton22.setText("Venda");
        jButton22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton22);

        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-qr-code-40.png"))); // NOI18N
        jButton23.setText("Recargas");
        jButton23.setHideActionText(true);
        jButton23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton23);

        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-supplier-40.png"))); // NOI18N
        jButton24.setText("Operadoras");
        jButton24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton24);

        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-product-40.png"))); // NOI18N
        jButton25.setText("Lista");
        jButton25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton25);

        jPanel4.add(jPanel8);

        jPanel14.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.GridLayout(1, 3));

        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("def");
        jPanel6.add(jButton8);

        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("night");
        jPanel6.add(jButton9);

        jPanel14.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setViewportView(jPanel14);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.WEST);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Matavele's\\Downloads\\Abstract-Wallpaper-HD-For-Desktop.jpg")); // NOI18N
        jPanel9.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        //create void for methode hide and show panel menu
        //        if (a == true) {
            //            hideshow(jPanel14, a);
            //            SwingUtilities.updateComponentTreeUI(this);
            //            //create methode change image
            //
            //            a = false;
            //        } else {
            //            hideshow(jPanel14, a);
            //            SwingUtilities.updateComponentTreeUI(this);
            //            a = true;
            //        }
        if (dr.isShow()) {
            dr.hide();
        } else {
            dr.show();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked

    }//GEN-LAST:event_jPanel12MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        jPopupMenu1.show(jButton7, WIDTH, 25);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        painelCliente = new ClienteR();
        jPanel9.removeAll();
        jPanel9.add(painelCliente, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed

        painelCateg = new CategoriaR();
        jPanel9.removeAll();
        jPanel9.add(painelCateg, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        painelVenda = new Venda();
        jPanel9.removeAll();
        jPanel9.add(painelVenda, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        painelProd = new ProdutoR();
        jPanel9.removeAll();
        jPanel9.add(painelProd, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        painelForn = new FornecedorR();
        jPanel9.removeAll();
        jPanel9.add(painelForn, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        painelLista = new ListaC();
        jPanel9.removeAll();
        jPanel9.add(painelLista, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        FreshUi fresh = (FreshUi) frame;
        fresh.setPanel(fresh.getLogin());
        fresh.setVisible(true);
        revalidate();
        repaint();

    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
