/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Painels;

import Controllers.OperadoraDAOImpl;
import Controllers.ListaDAOImpl;
import Controllers.ProdutosDAOImpl;
import Modelos.Categoria;
import Modelos.Cliente;
import Modelos.Operadora;
import Modelos.Produto;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matavele's
 */
public class ProdutoR extends javax.swing.JPanel {
    
    private ProdutosDAOImpl gestor;
    private OperadoraDAOImpl gero;
    private DefaultComboBoxModel model;
    
    private DefaultTableModel modelo;
    /**
     * Creates new form Venda
     */
    public ProdutoR() {
        gero = new OperadoraDAOImpl();
        gestor = new ProdutosDAOImpl();
        initComponents();
        add.putClientProperty("JButton.buttonType", "roundRect");
        edit.putClientProperty("JButton.buttonType", "roundRect");
        rmv.putClientProperty("JButton.buttonType", "roundRect");
        model = new DefaultComboBoxModel();
        modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Produto");
        modelo.addColumn("Compra");
        modelo.addColumn("Venda");
        modelo.addColumn("Quantidade");
        modelo.addColumn("Validade");
        modelo.addColumn("Fornecedor");
        modelo.addColumn("Entrada");
        
        tabela();
        combo();
    }
    
     public void combo(){
         List cat = gero.listarOperadoras();

        Iterator it = cat.iterator();
        
        while (it.hasNext()) {
            
           Operadora produto = (Operadora) it.next();
            String nome = produto.getNome();

            model.addElement(nome);
        }
        
        combox.setModel(model);
    }
    
    public void tabela(){
        modelo.setRowCount(0);
        
        List produtos = gestor.listarProdutos();
        
        Iterator it = produtos.iterator();
        
        while(it.hasNext()){
            Produto produto = (Produto) it.next();
            Object[] fila = new Object[8];
            fila[0] = produto.getId();
            fila[1] = produto.getNomeProduto();
            fila[2] = produto.getPreco();
            fila[3] = produto.getValor();
            fila[4] = produto.getQuantidadeProduto();
            fila[5] = produto.getFornecedor();
            fila[6] = produto.getValidadeProduto();
            fila[7] = produto.getEntrada();
            
            modelo.addRow(fila);
        }
        
        tabela.setModel(modelo);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        prcField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        vlrField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        qtdField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        combox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        rmv = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.BorderLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(450, 450));

        jPanel4.setPreferredSize(new java.awt.Dimension(450, 450));
        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane4);

        jPanel2.setLayout(new java.awt.GridLayout(11, 0));

        jLabel2.setText("Plano de Recarga");
        jPanel2.add(jLabel2);
        jPanel2.add(nomeField);

        jLabel1.setText("Preço de Compra");
        jPanel2.add(jLabel1);
        jPanel2.add(prcField);

        jLabel9.setText("Preço de Venda");
        jPanel2.add(jLabel9);

        vlrField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vlrFieldActionPerformed(evt);
            }
        });
        jPanel2.add(vlrField);

        jLabel10.setText("Quantidade no Stock");
        jPanel2.add(jLabel10);

        qtdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdFieldActionPerformed(evt);
            }
        });
        jPanel2.add(qtdField);

        jLabel11.setText("Operadora");
        jPanel2.add(jLabel11);

        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(combox);

        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        add.setText("Adicionar");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel3.add(add);

        edit.setText("Atualizar");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel3.add(edit);

        rmv.setText("Remover");
        jPanel3.add(rmv);

        jPanel2.add(jPanel3);

        jPanel5.add(jPanel2);

        jPanel4.add(jPanel5);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Produtos Existentes");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(572, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel4.add(jPanel1);

        jScrollPane2.setViewportView(jPanel4);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void vlrFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vlrFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vlrFieldActionPerformed

    private void qtdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdFieldActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
         String nome = nomeField.getText();
       double preco = Double.parseDouble(prcField.getText());
       double valor = Double.parseDouble(vlrField.getText());
       int quantidade = Integer.parseInt(qtdField.getText());
       
       int selectedIndex = combox.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um Fornecedor.");
            return;
        }
        
        List cat = gero.listarOperadoras();
        
        if (cat != null && selectedIndex >= 0 && selectedIndex < cat.size()) {
            Operadora prod = (Operadora) cat.get(selectedIndex);
            Produto cliente = new Produto(nome,new Date(),preco,valor,quantidade,prod);

            try {
                gestor.adicionarProduto(cliente);
                JOptionPane.showMessageDialog(null, "novo Produto adicionado!");
                nomeField.setText("");
                prcField.setText("");
                vlrField.setText("");
                qtdField.setText("");
                tabela();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Fornecedor selecionada inválida.");
        }
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
         List<Operadora> cs = gero.listarOperadoras();
        List<Produto> clientes = gestor.listarProdutos();
        int com = combox.getSelectedIndex();
        int selected = tabela.getSelectedRow();

        if (selected != -1) {
            Operadora cat = cs.get(com);
            String nome = nomeField.getText();
            double preco = Double.parseDouble( prcField.getText());
            double valor = Double.parseDouble(vlrField.getText());
            
            int qtd = Integer.parseInt(qtdField.getText());

            //            String nome = JOptionPane.showInputDialog("Editar nome do cliente:", modelo.getValueAt(selected, 1));
            //            String email = JOptionPane.showInputDialog("Editar email do cliente:", modelo.getValueAt(selected, 1));
            if (nome != null && !nome.isEmpty()) {
                int id = (int) modelo.getValueAt(selected, 0);
                Produto cliente = gestor.buscarProduto(id);
                        cliente.setNomeProduto(nome);
                        cliente.setPreco(preco);
                        cliente.setValor(valor);
                        cliente.setQuantidadeProduto(qtd);
                        
                        gestor.atualizarProdutos(cliente);
                        
                        JOptionPane.showMessageDialog(null, "Produto Atualizado!");
                tabela();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Produto para editar.");
        }
    }//GEN-LAST:event_editActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JComboBox<String> combox;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nomeField;
    private javax.swing.JTextField prcField;
    private javax.swing.JTextField qtdField;
    private javax.swing.JButton rmv;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField vlrField;
    // End of variables declaration//GEN-END:variables
}
