/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Painels;

import Controllers.OperadoraDAOImpl;
import Controllers.ListaDAOImpl;
import Controllers.ProdutosDAOImpl;
import Modelos.Categoria;
import Modelos.Cliente;
import Modelos.Operadora;
import Modelos.Produto;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matavele's
 */
public class ProdutoR extends javax.swing.JPanel {
    
    private ProdutosDAOImpl gestor;
    private OperadoraDAOImpl gero;
    private DefaultComboBoxModel model;
    
    private DefaultTableModel modelo;
    /**
     * Creates new form Venda
     */
    public ProdutoR() {
        gero = new OperadoraDAOImpl();
        gestor = new ProdutosDAOImpl();
        initComponents();
        model = new DefaultComboBoxModel();
        modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Produto");
        modelo.addColumn("Compra");
        modelo.addColumn("Venda");
        modelo.addColumn("Quantidade");
        modelo.addColumn("Validade");
        modelo.addColumn("Fornecedor");
        modelo.addColumn("Entrada");
        
        tabela();
        combo();
    }
    
     public void combo(){
         List cat = gero.listarOperadoras();

        Iterator it = cat.iterator();
        
        while (it.hasNext()) {
            
           Operadora produto = (Operadora) it.next();
            String nome = produto.getNome();

            model.addElement(nome);
        }
        
        combox.setModel(model);
    }
    
    public void tabela(){
        modelo.setRowCount(0);
        
        List produtos = gestor.listarProdutos();
        
        Iterator it = produtos.iterator();
        
        while(it.hasNext()){
            Produto produto = (Produto) it.next();
            Object[] fila = new Object[8];
            fila[0] = produto.getId();
            fila[1] = produto.getNomeProduto();
            fila[2] = produto.getPreco();
            fila[3] = produto.getValor();
            fila[4] = produto.getQuantidadeProduto();
            fila[5] = produto.getFornecedor();
            fila[6] = produto.getValidadeProduto();
            fila[7] = produto.getEntrada();
            
            modelo.addRow(fila);
        }
        
        tabela.setModel(modelo);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        prcField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        vlrField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        qtdField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        combox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(2, 2));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(11, 0));

        jLabel2.setText("Produto");
        jPanel2.add(jLabel2);
        jPanel2.add(nomeField);

        jLabel1.setText("Preço de Compra");
        jPanel2.add(jLabel1);
        jPanel2.add(prcField);

        jLabel9.setText("Preço de Venda");
        jPanel2.add(jLabel9);

        vlrField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vlrFieldActionPerformed(evt);
            }
        });
        jPanel2.add(vlrField);

        jLabel10.setText("Quantidade no Stock");
        jPanel2.add(jLabel10);

        qtdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdFieldActionPerformed(evt);
            }
        });
        jPanel2.add(qtdField);

        jLabel11.setText("Fornecedor");
        jPanel2.add(jLabel11);

        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(combox);

        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Adicionar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Editar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Eliminar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4);

        jPanel2.add(jPanel3);

        add(jPanel2);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        add(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        add(jPanel1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        add(jScrollPane4);
    }// </editor-fold>//GEN-END:initComponents

    private void vlrFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vlrFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vlrFieldActionPerformed

    private void qtdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdFieldActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
       String nome = nomeField.getText();
       double preco = Double.parseDouble(prcField.getText());
       double valor = Double.parseDouble(vlrField.getText());
       int quantidade = Integer.parseInt(qtdField.getText());
       
       int selectedIndex = combox.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um Fornecedor.");
            return;
        }
        
        List cat = gero.listarOperadoras();
        
        if (cat != null && selectedIndex >= 0 && selectedIndex < cat.size()) {
            Operadora prod = (Operadora) cat.get(selectedIndex);
            Produto cliente = new Produto(nome,new Date(),preco,valor,quantidade,prod);

            try {
                gestor.adicionarProduto(cliente);
                JOptionPane.showMessageDialog(null, "novo Produto adicionado!");
                nomeField.setText("");
                prcField.setText("");
                vlrField.setText("");
                qtdField.setText("");
                tabela();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Fornecedor selecionada inválida.");
        }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        List<Operadora> cs = gero.listarOperadoras();
        List<Produto> clientes = gestor.listarProdutos();
        int com = combox.getSelectedIndex();
        int selected = tabela.getSelectedRow();

        if (selected != -1) {
            Operadora cat = cs.get(com);
            String nome = nomeField.getText();
            double preco = Double.parseDouble( prcField.getText());
            double valor = Double.parseDouble(vlrField.getText());
            
            int qtd = Integer.parseInt(qtdField.getText());

            //            String nome = JOptionPane.showInputDialog("Editar nome do cliente:", modelo.getValueAt(selected, 1));
            //            String email = JOptionPane.showInputDialog("Editar email do cliente:", modelo.getValueAt(selected, 1));
            if (nome != null && !nome.isEmpty()) {
                int id = (int) modelo.getValueAt(selected, 0);
                Produto cliente = gestor.buscarProduto(id);
                        cliente.setNomeProduto(nome);
                        cliente.setPreco(preco);
                        cliente.setValor(valor);
                        cliente.setQuantidadeProduto(qtd);
                        
                        gestor.atualizarProdutos(cliente);
                        
                        JOptionPane.showMessageDialog(null, "Produto Atualizado!");
                tabela();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Produto para editar.");
        }
    }//GEN-LAST:event_jPanel5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nomeField;
    private javax.swing.JTextField prcField;
    private javax.swing.JTextField qtdField;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField vlrField;
    // End of variables declaration//GEN-END:variables
}
