/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Painels;

import Controllers.ClienteDAOImpl;
import Controllers.ListaDAOImpl;
import Controllers.VendaDAOImpl;
import Modelos.Categoria;
import Modelos.Cliente;
import Modelos.Funcionario;
import Modelos.Operadora;
import Modelos.Lista;
import Modelos.Produto;
import Modelos.Venda;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matavele's
 */
public class VendaR extends javax.swing.JPanel {
    
    private ListaDAOImpl gestor;
    private ClienteDAOImpl gestor1;
    private VendaDAOImpl gestor2;
    private DefaultComboBoxModel model;
    private DefaultTableModel modelo;
    private BufferedImage image;
    private Funcionario func;
    private double total;
    /**
     * Creates new form Venda
     */
    public VendaR(Funcionario func) {
        this.func= (Funcionario) func;
        gestor = new ListaDAOImpl();
        gestor1 = new ClienteDAOImpl();
        gestor2 = new VendaDAOImpl();
        initComponents();
        try {
            // Carregue a imagem desejada (substitua o caminho pelo caminho do seu arquivo de imagem)
            image = ImageIO.read(new File("src//Icones//Abstract-Wallpaper-HD-For-Desktop.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        vndr.putClientProperty("JButton.buttonType", "roundRect");
        edit.putClientProperty("JButton.buttonType", "roundRect");
        rmv.putClientProperty("JButton.buttonType", "roundRect");
        cncl.putClientProperty("JButton.buttonType", "roundRect");
        modelo = new DefaultTableModel();
        model = new DefaultComboBoxModel();
        
        modelo.addColumn("Id");
        modelo.addColumn("Produto");
        modelo.addColumn("Quantidade");
        combo();
    }
    
     @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            g.drawImage(image, 0, 0, this);
            
        }else{
           JOptionPane.showInternalMessageDialog(null, "eeee");
        }
    }
    public void combo(){
         List cat = gestor1.listarCliente();

        Iterator it = cat.iterator();
        
        while (it.hasNext()) {
            
           Cliente produto = (Cliente) it.next();
            String nome = produto.getNome();

            model.addElement(nome);
        }
        
        combox.setModel(model);
    }
    
    public void tabela(){
        total = 0;
        modelo.setRowCount(0);
        int selected = combox.getSelectedIndex();
        
        if(selected == -1){
            JOptionPane.showMessageDialog(null, "selecione o Cliente!");
            return;
        }
        
        List clientes = gestor1.listarCliente();
        
        if (clientes != null && selected>= 0 && selected < clientes.size()){
            Cliente cliente = (Cliente) clientes.get(selected);
            
            List vens = gestor.buscarListaCliente(cliente);
            
            Iterator it = vens.iterator();
            
            while(it.hasNext()){
                Lista li = (Lista) it.next();
                
                Object[] fila = new Object[3];
                
                fila[0] = li.getCliente().getId();
                fila[1] = li.getProduto().getNomeProduto();
                fila[2] = li.getQuantidade();
                
                total += li.getTotal();
                
                modelo.addRow(fila);
                
            }
            tabela.setModel(modelo);
        }
//        List<Venda> vendas = gestor.buscarListaCliente(cliente);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder8 = new com.raven.swing.PanelBorder();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        panelBorder9 = new com.raven.swing.PanelBorder();
        jLabel7 = new javax.swing.JLabel();
        nomeField3 = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        add3 = new javax.swing.JButton();
        edit4 = new javax.swing.JButton();
        rmv4 = new javax.swing.JButton();
        panelBorder2 = new com.raven.swing.PanelBorder();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelBorder6 = new com.raven.swing.PanelBorder();
        Cliente = new javax.swing.JLabel();
        combox = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tPane = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        valorField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        panelBorder1 = new Views.Painels.PanelBorder();
        vndr = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        cncl = new javax.swing.JButton();
        rmv = new javax.swing.JButton();
        panelBorder3 = new com.raven.swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        panelBorder8.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane9.setViewportView(jTextArea5);

        panelBorder8.add(jScrollPane9);

        panelBorder9.setLayout(new java.awt.GridLayout(7, 0, 5, 0));

        jLabel7.setText("Nome da Categoria");
        panelBorder9.add(jLabel7);

        nomeField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeField3ActionPerformed(evt);
            }
        });
        panelBorder9.add(nomeField3);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panelBorder9.add(jPanel26);

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panelBorder9.add(jPanel27);

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panelBorder9.add(jPanel28);

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panelBorder9.add(jPanel29);

        jPanel30.setLayout(new java.awt.GridLayout(1, 3, 1, 0));

        add3.setText("Registrar");
        add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add3ActionPerformed(evt);
            }
        });
        jPanel30.add(add3);

        edit4.setText("Alterar");
        jPanel30.add(edit4);

        rmv4.setText("Remover");
        rmv4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmv4ActionPerformed(evt);
            }
        });
        jPanel30.add(rmv4);

        panelBorder9.add(jPanel30);

        panelBorder8.add(panelBorder9);

        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        panelBorder2.setPreferredSize(new java.awt.Dimension(500, 224));
        panelBorder2.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        panelBorder2.add(jScrollPane4);

        panelBorder6.setLayout(new java.awt.GridLayout(8, 0, 5, 0));

        Cliente.setText("Cliente");
        panelBorder6.add(Cliente);

        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxActionPerformed(evt);
            }
        });
        panelBorder6.add(combox);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        jLabel8.setText("Total da Lista");
        jPanel8.add(jLabel8);

        tPane.setEditable(false);
        tPane.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(tPane);

        jPanel8.add(jScrollPane3);

        panelBorder6.add(jPanel8);

        jLabel3.setText("Valor Pago");
        panelBorder6.add(jLabel3);
        panelBorder6.add(valorField);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        jLabel4.setText("Trocos");
        jPanel7.add(jLabel4);

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(jTextPane1);

        jPanel7.add(jScrollPane2);

        panelBorder6.add(jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        panelBorder6.add(jPanel1);

        panelBorder1.setLayout(new java.awt.GridLayout(1, 4));

        vndr.setText("Vender");
        vndr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vndrActionPerformed(evt);
            }
        });
        panelBorder1.add(vndr);

        edit.setText("Atualizar");
        panelBorder1.add(edit);

        cncl.setText("Cancelar");
        cncl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnclActionPerformed(evt);
            }
        });
        panelBorder1.add(cncl);

        rmv.setText("Eliminar");
        panelBorder1.add(rmv);

        panelBorder6.add(panelBorder1);

        panelBorder2.add(panelBorder6);

        add(panelBorder2);

        panelBorder3.setPreferredSize(new java.awt.Dimension(650, 250));
        panelBorder3.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Lista de Recargas do Cliente");
        panelBorder3.add(jLabel1, java.awt.BorderLayout.NORTH);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        panelBorder3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(panelBorder3);
    }// </editor-fold>//GEN-END:initComponents

    private void comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxActionPerformed
        tabela();
        tPane.setText(""+total);
    }//GEN-LAST:event_comboxActionPerformed

    private void vndrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vndrActionPerformed
       int quantidade = Integer.parseInt(valorField.getText());
       double valor = Double.parseDouble(valorField.getText());
       

        int selectedIndex = combox.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um Cliente.");
            return;
        }
        
        List clientes = gestor1.listarCliente();
        
      
    if ((clientes != null && selectedIndex >= 0 && selectedIndex < clientes.size())) {
          Cliente cliente = (Cliente) clientes.get(selectedIndex);
          List cesto = gestor.buscarListaCliente(cliente);
          try {
            Venda venda = new Venda(func,cesto,quantidade);
            venda.setValorPago(total);
            gestor2.efetuarVenda(venda);
            JOptionPane.showMessageDialog(null, "Venda efetuada!");
        } catch (Exception e) {
        }
    }else{
        JOptionPane.showMessageDialog(null, "nao existe cliente");
    }
//            Produto prod = (Produto) cat.get(selectedIndex1);
//
//            Cliente cliente = (Cliente) cat2.get(selectedIndex);
//            List cat = gestor.buscarListaCliente(cliente);
//            List<Lista> lc = gestor.buscarListaCliente(cliente);
//
//            try {
//                Lista list = new Lista(cliente, prod, quantidade);
//                prod.setQuantidadeProduto(list.getRemanescente());
//                gestor1.atualizarProdutos(prod);
//                try {
//                    gestor.adicionarLista(list);
//                    JOptionPane.showMessageDialog(null, "Recarga adicionada a lista de compras!");
//                    qtdField.setText("");
//                    tabela(cliente);
//                } catch (Exception e) {
//                    JOptionPane.showMessageDialog(null, e);
//                }
//            } catch (NullPointerException e) {
//                JOptionPane.showMessageDialog(null, "excedeu o limite" + e.getMessage());
//            }
//
//        } else {
//            JOptionPane.showMessageDialog(null, "Recarga/Cliente selecionado inválido.");
//        }
    }//GEN-LAST:event_vndrActionPerformed

    private void cnclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnclActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnclActionPerformed

    private void nomeField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeField3ActionPerformed

    private void add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add3ActionPerformed
        
    }//GEN-LAST:event_add3ActionPerformed

    private void rmv4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmv4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmv4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cliente;
    private javax.swing.JButton add3;
    private javax.swing.JButton cncl;
    private javax.swing.JComboBox<String> combox;
    private javax.swing.JButton edit;
    private javax.swing.JButton edit4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField nomeField3;
    private Views.Painels.PanelBorder panelBorder1;
    private com.raven.swing.PanelBorder panelBorder2;
    private com.raven.swing.PanelBorder panelBorder3;
    private com.raven.swing.PanelBorder panelBorder6;
    private com.raven.swing.PanelBorder panelBorder8;
    private com.raven.swing.PanelBorder panelBorder9;
    private javax.swing.JButton rmv;
    private javax.swing.JButton rmv4;
    private javax.swing.JTextPane tPane;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField valorField;
    private javax.swing.JButton vndr;
    // End of variables declaration//GEN-END:variables
}
