package Modelos;
// Generated 11/set/2023 18:45:06 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;

/**
 * Pedidos generated by hbm2java
 */
@Entity
public class Pedidos  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pedido_id_sequence")
    @SequenceGenerator(name = "pedido_id_sequence", sequenceName = "pedido_id_sequence", allocationSize = 1)
    @Column(name = "PEDIDO_ID", precision = 8, scale = 0)
     private int pedidoId;
    
    @Column(name = "CLIENTE_ID", precision = 8, scale = 0)
     private Clientes clientes;
     
    @Column(name = "PRODUTO_ID", precision = 8, scale = 0)
     private Produtos produtos;
     
     @Column(name = "QUANTIDADE", precision = 8, scale = 0)
     private int quantidade;
     
    @Column(name = "DATA_PEDIDO", length = 7)
    @Temporal(javax.persistence.TemporalType.DATE)
     private Date dataPedido;

    public Pedidos() {
    }

	
    public Pedidos(int pedidoId, int quantidade) {
        this.pedidoId = pedidoId;
        this.quantidade = quantidade;
    }
    public Pedidos(int pedidoId, Clientes clientes, Produtos produtos, int quantidade, Date dataPedido) {
       this.pedidoId = pedidoId;
       this.clientes = clientes;
       this.produtos = produtos;
       this.quantidade = quantidade;
       this.dataPedido = dataPedido;
    }
   
    public int getPedidoId() {
        return this.pedidoId;
    }
    
    public void setPedidoId(int pedidoId) {
        this.pedidoId = pedidoId;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public Date getDataPedido() {
        return this.dataPedido;
    }
    
    public void setDataPedido(Date dataPedido) {
        this.dataPedido = dataPedido;
    }




}


