package Modelos;
// Generated 11/set/2023 18:45:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;

/**
 * Produtos generated by hbm2java
 */
public class Produtos  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "produto_id_sequence")
    @SequenceGenerator(name = "produto_id_sequence", sequenceName = "produto_id_sequence", allocationSize = 1)
    @Column(name = "PRODUTO_ID", precision = 8, scale = 0)
     private int produtoId;
    
    @Column(name = "NOME", length = 50, nullable = false)
     private String nome;
     
    @Column(name = "PRECO", precision = 10, scale = 0, nullable = false)
     private long preco;
     
    @OneToMany(mappedBy = "produto", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
     private Set pedidoses = new HashSet(0);

    public Produtos() {
    }

	
    public Produtos(int produtoId, String nome, long preco) {
        this.produtoId = produtoId;
        this.nome = nome;
        this.preco = preco;
    }
    public Produtos(int produtoId, String nome, long preco, Set pedidoses) {
       this.produtoId = produtoId;
       this.nome = nome;
       this.preco = preco;
       this.pedidoses = pedidoses;
    }
   
    public int getProdutoId() {
        return this.produtoId;
    }
    
    public void setProdutoId(int produtoId) {
        this.produtoId = produtoId;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public long getPreco() {
        return this.preco;
    }
    
    public void setPreco(long preco) {
        this.preco = preco;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }




}


